package com.knowyourneighborhood;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class LoginController {
	
	@Autowired
	private PasswordEncoder pwdencode;
	
    @RequestMapping(value="/login",  method= RequestMethod.GET)
    public String onLogin() {
        return "login";
    }

    @RequestMapping(value="/login_error")
    public String onLoginError(Model model) {
        String error_msg = "Incorrect user or password. Please re-enter.";
        model.addAttribute("error_string", error_msg);
        System.out.println(error_msg);
        return "login";
    }
    // Get Encoded password
    @RequestMapping(value="/passwordEncode",  method= RequestMethod.GET)
    public String passwordEncodeTest(Model model) {        
    	String encodePwd=pwdencode.encode("maven123456");
    	boolean compare = pwdencode.matches("maven123456", encodePwd);
    	model.addAttribute("encodePwd",encodePwd);
    	System.out.println("Generated by Password Encode is "+encodePwd);
    	System.out.println("Comparison" + compare);
    	
        return "password";
    }
}
